### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by pilo1337** [paranerd/alexa-skill-shopping-list#7]
Hi,

Nice project, but i have troubles to compile it.
I followed your guide, at the point "ask deploy" i got the following error:

ask deploy
Deploy configuration loaded from ask-resources.json
Deploy project for profile [default]

==================== Deploy Skill Metadata ====================
Uploading the entire skill package and building the models. Normally it takes a few minutes...
  ✔ Received a new skill id: amzn1.ask.skill.aeXXXXXXXXXXXXXXXXXXXXXX
  ✔ Importing skill using import id: amzn1.ask-package.import.XXXXXXXXXXXXXXXXXXXXXX
  ✔ [Interaction Model] build is complete.
Skill package deployed and all models built successfully.
Skill ID: amzn1.ask.skill.aeXXXXXXXXXXXXXXXXXXXXXX

==================== Build Skill Code ====================
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 71 packages, and audited 72 packages in 3s

39 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Skill code built successfully.
Code for region default built to /root/alexa-skill-shopping-list/.ask/lambda/build.zip successfully with build flow NodeJsNpmBuildFlow.

==================== Deploy Skill Infrastructure ====================
[Error]: [Error]: Built-in skill infrastructure type "@ask-cli/lambda-deployer" failed to load.
SyntaxError: Unexpected token '.'

What am i doing wrong?

thanks 4 help

**Comment by paranerd** [comment]
Just tried re-deploying myself. Worked like a charm.

Also, according to the output `Skill code built successfully.` it doesn't seem to be an issue with the code.

Maybe try updating `ask-cli`:

```bash
sudo npm update -g ask-cli
```

For me the output of `ask -V` is `2.30.5`

**Comment by pilo1337** [comment]
my ask version is the same.
seems to be some issue with the uploading process for the lambda function.. 
which privileges do the account need in the IAM of AWS?

**Comment by paranerd** [comment]
Mine uses the default `AWSLambdaBasicExecutionRole`

**Comment by pilo1337** [comment]
i managed it by uploading the build.zip manually and connected it to the skill, works like a charm! i think its a strange thing with the virtual machine i used, crappy ubuntu stuff.. nvm.

Thank you!
